version: "2"

services:
  backend:
    build: .
    ports: 
      - 3000:3000
      - 9229:9229 # debuger port
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run start:docker
    environment:
      PORT: 3000